### ISSUE TITLE
Do you have pre-trained generator and classifier for Controllable Generation in course1 week4?

### ISSUE THREAD

**Issue by linhanxiao** [ijelliti/Deeplearning.ai-GAN-Specialization-Generative-Adversarial-Networks#11]
Do you have pre-trained generator and classifier for Controllable Generation in course1 week4?

**Comment by rust0258** [comment]
@linhanxiao, I uploaded the 2 pre-trained pth files [here](https://github.com/ijelliti/Deeplearning.ai-GAN-Specialization-Generative-Adversarial-Networks/tree/master/1%20-%20Build%20Basic%20Generative%20Adversarial%20Networks/Week%204)
