### ISSUE TITLE
pix2pix needs  data from directory maps

### ISSUE THREAD

**Issue by wormcode** [ijelliti/Deeplearning.ai-GAN-Specialization-Generative-Adversarial-Networks#18]
in pix2pix file, 
I found exception:

FileNotFoundError: [Errno 2] No such file or directory: 'maps'
from code
dataset = torchvision.datasets.ImageFolder("maps", transform=transform)

I think it must be lost some data.
would you please fix this.
many thanks!

**Comment by rust0258** [comment]
@wormcode some data are not download-able from the labs. I think this is one of them
