### ISSUE TITLE
pix2pix_15000.pth in the folder is a html file

### ISSUE THREAD

**Issue by wormcode** [ijelliti/Deeplearning.ai-GAN-Specialization-Generative-Adversarial-Networks#19]
the content of  pix2pix_15000.pth  is html, not the weights at all. You have cheated by the ipython notebook(this must be a notebook bug) UI download option by right click mouse.

the correct download operation is check the item that would be download, by doing this , the download option appear in the web page just above the beginning of the items.

**Comment by rust0258** [comment]
@wormcode sorry I no more have access to the course labs, if you still have please fork and upload it
